server.port=8081
spring.application.name=Hotel
spring.datasource.url=jdbc:${DB_USERNAME}ql://localhost:5432/HotelDB
spring.datasource.driverClassName=org.${DB_USERNAME}ql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=mateusz
spring.security.user.password=m@123